/*Tutorial from the authority, which is quite marvellous. As follows:
Notice that the states T = abab ... abab and T = baba ... baba (with the same length) are equivalent by reflection (you can
simply use the opposite operation for the rest of the iteration).

Initially, if n is odd, you can only append a to S. Therefore, S1 needs to be a if n is odd. The rest of the string is equivalent to when n
is even, so WLOG we will assume that n is even.

When T = abab ... abab, you can't use the same letter twice in a row because the first and last letters of T will be the same on the
next iteration. Therefore, when you look at the letters of S in groups of 2, they should be either ab or ba.

Therefore, the string S generated by the algorithm must satisfy the following conditions:

· S1 is a if n is odd;
. Szi not equal to S2i+1 if n is odd;
· S2i-1 not equal S2i if n is even.

The '?'-s in the input don't make a difference in the solution after this observation. The problem is solved in O(n) time.*/
#include <bits/stdc++.h>
using namespace std;

int main(){
    ios::sync_with_stdio(false);
    cin.tie(0);
    int tt; cin>>tt;
    while(tt--){
        int n; cin>>n;
        string s;
        cin>>s;
        bool flag=true;
        if(n%2==0){
            for(int i=1;i<n;i+=2){
                if(s[i]==s[i-1]&&s[i]!='?'){
                    flag=false;
                    break;
                }
            }
        }else{
            if(s[0]=='b'){
                flag=false;
            }else{
                for(int i=2;i<n;i+=2){
                    if(s[i]==s[i-1]&&s[i]!='?'){
                        flag=false;
                        break;
                    }
                }
            }
        }
        if(flag) cout<<"YES"<<endl;
        else cout<<"NO"<<endl;
    }
    return 0;
}